apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "chart.fullname" . }}
  labels:
    app: {{ template "chart.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "chart.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        {{ template "mindaro.pod.volumes" . }}
      initContainers:
        {{ template "mindaro.pod.initcontainers" . }}
      containers:
        {{ template "mindaro.pod.containers" . }}
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
            {{- if and .Values.development.enabled .Values.development.debugPort }}
            - containerPort: {{ .Values.development.debugPort }}
            {{- end }}
          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ template "chart.name" . }}-redis
                  key: host
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ template "chart.name" . }}-redis
                  key: port
            - name: REDIS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "chart.name" . }}-redis
                  key: key
          {{- if .Values.development.enabled }}
          {{- if .Values.development.command }}
          command: {{ toJson .Values.development.command }}
          {{- end }}
          {{- if .Values.development.args }}
          args: {{ toJson .Values.development.args }}
          {{- end }}
          {{- else }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.internalPort }}
          {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
